### ISSUE TITLE
Make ERROR

### ISSUE THREAD

**Issue by NotSoEthical** [0x36/VPNPivot#2]
`In file included from pivots.c:26:0:
../include/etn.h:38:28: fatal error: openssl/crypto.h:`

How to fix?

**Comment by 0x36** [comment]
Hi , you should install libssl-dev

**Comment by NotSoEthical** [comment]
Thanks))))

**Comment by luckypoem** [comment]
hello.
on my mac.

yudeMacBook-Air:vpnpivot brite$ make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..   -I/usr/include -ggdb -DUSE_SSL -DUSE_POLL -I../include  -g -O2 -MT pivots.o -MD -MP -MF .deps/pivots.Tpo -c -o pivots.o pivots.c
In file included from pivots.c:26:
../include/etn.h:30:10: fatal error: 'linux/if_ether.h' file not found
#include <linux/if_ether.h>
         ^
1 error generated.
make[2]: *** [pivots.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
yudeMacBook-Air:vpnpivot brite$

how to fix the issue : "fatal error: 'linux/if_ether.h' file not found"?
